language: c++
compiler: gcc
os: linux
sudo: false
addons:
  apt:
    packages:
      - g++-5
    sources: &sources
      - ubuntu-toolchain-r-test
script:
  - export CXX=g++-5
  - make && ./libawait-test
