cc_library(
    name = "libawait",
    deps = [
        "//cpp-libsingleton:singleton",
        ],
    srcs = [
        "await/detail/linux_fd_task.cpp",
        "await/detail/linux_fiber.cpp",
        "await/detail/linux_run.cpp",
        "await/detail/linux_tcp.cpp",
        "await/detail/linux_timer.cpp",
        "await/detail/parallel.cpp",
        "await/detail/result.cpp",
        "await/detail/stream.cpp",
        "await/detail/task.cpp",

        "await/detail/command.h",
        "await/detail/command_impl.h",
        "await/detail/command_intf.h",
        "await/detail/command_ptr_fwd.h",
        "await/detail/command_ptr_impl.h",
        "await/detail/intrusive_list.h",
        "await/detail/linux_error.h",
        "await/detail/linux_fd_task.h",
        "await/detail/linux_scheduler.h",
        "await/detail/loop_impl.h",
        "await/detail/result_impl.h",
        "await/detail/result_kind.h",
        "await/detail/run_impl.h",
        "await/detail/task_fwd.h",
        "await/detail/task_impl.h",
        "await/detail/task_storage.h",
        "await/detail/task_traits.h",
        "await/detail/task_traits_impl.h",
        "await/detail/task_utils_fwd.h",
        "await/detail/task_utils_impl.h",
        "await/detail/then_impl.h",
        "await/detail/then_traits.h",
        ],
    hdrs = [
        "await/cancel.h",
        "await/coroutine.h",
        "await/fiber.h",
        "await/result.h",
        "await/run.h",
        "await/stream.h",
        "await/task.h",
        "await/tcp.h",
        "await/timer.h",
        ],
    includes = ["."],
    )

cc_test(
    name = "libawait_test",
    deps = [
        "libawait",
        "//cppmutest:mutest",
        ],
    srcs = [
        "test/fiber_test.cpp",
        "test/parallel_test.cpp",
        "test/result_test.cpp",
        "test/then_test.cpp",
        "test/timer_test.cpp",
        "test/tcp_test.cpp",
        "test/task_test.cpp",
        ],
    )
